concurrent = 4
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "runner1"
  url = "https://gitlab.domain.com:6443"
  id = 1
  token = "glrt-PFU-8sa312u-zoZnaz5E"
  token_obtained_at = 2024-01-15T01:24:21Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  tls-ca-file = "/etc/gitlab-runner/ssl/ca.crt"
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.docker]
    tls_verify = false
    image = "ruby:2.7"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0
    extra_hosts = ["gitlab.domain.com:169.254.100.2"]
